In [2]:
import numpy as np

In [3]:
# creating array with step-size
arr = np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [4]:
# initilizing list
list1 = input("enter the nos - ")
list2 = input("enter the nos - ")

# converting list to array
arr1 = np.array([list1])
arr2 = np.array([list2])

# concatenation of array
arr = np.concatenate((arr1, arr2))
print("the cocatenated array - ", arr)

# sorting of array
arr0 = np.sort(arr1, axis = 0)        
print ("Along first axis : \n", arr0)

a = np.sort(arr2, axis = None)        
print ("Along none axis : \n", a)

enter the nos - 1 2 3 4 5
enter the nos - 6 7 8 9 10
the cocatenated array -  ['1 2 3 4 5' '6 7 8 9 10']
Along first axis : 
 ['1 2 3 4 5']
Along none axis : 
 ['6 7 8 9 10']


In [5]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print("No. of dimensions: ", arr.ndim)
print("Size of array: ", arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
No. of dimensions:  2
Size of array:  9


In [6]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)

# by adding new axis
arr1 = arr[np.newaxis, :]
print(arr1.shape)

# by expanding dimension
arr2 = np.expand_dims(arr, axis=1)
print(arr2.shape)

(6,)
(1, 6)
(6, 1)


In [7]:
a1 = np.array([[7, 2],
               [1, 9]])
a2 = np.array([[0, 5],
               [8, 0]])
# vertical stacking 
print("Vertical stacking:\n", np.vstack((a1, a2))) 
  
# horizontal stacking 
print("\nHorizontal stacking:\n", np.hstack((a1, a2)))

Vertical stacking:
 [[7 2]
 [1 9]
 [0 5]
 [8 0]]

Horizontal stacking:
 [[7 2 0 5]
 [1 9 8 0]]


In [8]:
a = np.array([11, 11, 12, 21, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20, 16, 18, 19])

# get unique values
unique_values = np.unique(a)
print(unique_values)

# count unique values
unique_values,occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[11 12 13 14 15 16 17 18 19 20 21]
[3 2 2 2 1 2 1 2 2 1 1]
